name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: HEMTT Build
        uses: docker://hemtt/hemtt:0.6.1
        with:
          entrypoint: hemtt
          args: build --release

      - name: Upload mod
        uses: actions/upload-artifact@v1
        with:
          name: '@anrop_cba_settings'
          path: releases/1.0.0/@anrop_cba_settings

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check settings order
        run: diff --color=always -u <(cat addons/userconfig/cba_settings.sqf | grep '\S') <(cat addons/userconfig/cba_settings.sqf | grep '\S' | sort --ignore-case)
